# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.cache/wt [current_project]
set_property parent.project_path C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.srcs/sources_1/new/onebitadder.v
  C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.srcs/sources_1/new/inverter.v
  C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.srcs/sources_1/new/fourbitadder.v
  C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.srcs/sources_1/new/twos_complement.v
  C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.srcs/sources_1/new/two_to_one_multiplexer.v
  C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.srcs/sources_1/new/subtractor.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.srcs/constrs_1/imports/Vivado_lab/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/yanhan/Vivado_lab/onebitadder/onebitadder.srcs/constrs_1/imports/Vivado_lab/Basys3_Master.xdc]


synth_design -top subtractor -part xc7a35tcpg236-1


write_checkpoint -force -noxdef subtractor.dcp

catch { report_utilization -file subtractor_utilization_synth.rpt -pb subtractor_utilization_synth.pb }
